name: "PNPM Cache"

description: "Action to cache PNPM dependencies"

inputs:
  path:
    description: "Path to the PNPM cache directory."
    required: true
  key:
    description: "Cache key."
    required: true
  restore-keys:
    description: "Cache keys to restore."
    required: true

runs:
  using: "composite"
  steps:
    - name: 'pnpm-cache'
      uses: actions/cache@v4
      with:
        path: ${{ inputs.path }}
        key: ${{ inputs.key }}
        restore-keys: ${{ inputs.restore-keys }}
